### ISSUE TITLE
Rewrite README and add LICENSE

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutarch-context-builder#11]
Once #5 is merged, we should rewrite the README with expanded examples (or point to examples in the code) and add a LICENSE file.

Also would be good to indicate what parts of phase-1 validation this can do (doesn't need a ton of detail)

**Comment by peter-mlabs** [comment]
Reassigning this one to @SeungheonOh.

**Comment by SeungheonOh** [comment]
what kind of license do we want here? Was it apache?

**Comment by kozross** [comment]
@SeungheonOh Unless I am mistaken, Apache 2.0 is what all Liqwid libs are under.

**Comment by SeungheonOh** [comment]
Got it. I'll work on README and samples tomorrow.

**Comment by peter-mlabs** [comment]
Yep, Apache 2.0. Thanks!
