### ISSUE TITLE
The reference inputs are not passed in

### ISSUE THREAD

**Issue by arjaz** [Liqwid-Labs/plutarch-context-builder#27]
The collected reference inputs should be passed in when constructing the resulting context

https://github.com/Liqwid-Labs/plutarch-context-builder/blob/cc91cd134ce01e280df3b0ce09a25ede54dbf9b6/src/Plutarch/Context/Spending.hs#L190-L196

https://github.com/Liqwid-Labs/plutarch-context-builder/blob/318fbdd10e18d3441cd1293c5f5bbe3c4300c58d/src/Plutarch/Context/Minting.hs#L131-L137

**Comment by SeungheonOh** [comment]
It's fixed: c3d485a2de0e0f624d44e84ede9e9173a3d7fe21

I mistakenly pushed it directly to main
